name: API Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Установка зависимостей
        run: pip install requests pytest

      - name: Запуск тестов
        run: pytest test_api.py -v